Mehrdad/registration engine (WIP)
SaltyJoke/Image-Registration pull request #9
Opened 2024-03-14 16:51 UTC by mehrdadnekopour

2024-03-19 02:41 UTC, shahe650 commented on poc/QtImageRegistration/engine.cpp
> +    return alignedImage;
Are we returning the matrix or the image? The comment says matrix, but the variable name says image. The consumer wants the matrix.

2024-03-19 20:47 UTC, mehrdadnekopour commented on poc/QtImageRegistration/engine.cpp
> +    return alignedImage;
yes these 2 last lines are remaining to test previewing result , and have to get commented out when using the API

2024-03-21 04:09 UTC, shahe650 commented on poc/QtImageRegistration/engine.cpp
> +    return alignedImage;
Then please change the comment to "Will change to return homography for the API".

2024-03-21 04:28 UTC, shahe650 commented on poc/QtImageRegistration/image_utils.cpp
> +    image = imdecode(Mat(buffer), IMREAD_UNCHANGED);
If I understand, here you want to read the ".bin" file written from "eventHandling.ts". Does this work? I'm surprised if it works. You didn't provide the width and height.

2024-03-21 04:39 UTC, shahe650 commented on poc/QtImageRegistration/server.cpp
> +            Engine* registrationEngine = new Engine(this, imageData1, imageData2);
Here too, image width and height are not passed. Does it work?

2024-03-21 21:59 UTC, shahe650 commented on poc/QtImageRegistration/image_utils.cpp
> +    image = imdecode(Mat(buffer), IMREAD_UNCHANGED);
As you explained to me, the binary is a full image that OpenCV can parse. Then no problem.

2024-03-21 21:59 UTC, shahe650 commented on poc/QtImageRegistration/server.cpp
> +            Engine* registrationEngine = new Engine(this, imageData1, imageData2);
As you explained to me, the binary is a full image that OpenCV can parse. Then no problem.

2024-03-22 04:10 UTC, yoshi-nh commented on poc/QtImageRegistration/knowledge.md
This file provide the investigated result and we can share it.  
It's very noce!

2024-03-22 21:06 UTC, mehrdadnekopour commented on poc/QtImageRegistration/engine.cpp
> +    return alignedImage;
Sure, Done

2024-03-28 11:32 UTC, yoshi-nh requested changes

2024-03-28 11:32 UTC, yoshi-nh commented on poc/QtImageRegistration/server.cpp
> +    if (this->m_socket && this->m_socket->state() == QAbstractSocket::ConnectedState) {
I get exception here.

![image](https://github.com/SaltyJoke/Image-Registration/assets/54787014/a4b777fd-8e36-4af8-9b49-4a343cf76b8f)

2024-03-28 11:32 UTC, yoshi-nh commented on poc/QtImageRegistration/server.cpp
> +    qDebug() << 'HANDLE DATA RECEIVED CALLED';
I got C2015 error while building in Qt project.
I think it is recognized as single character since it is surrounded by '' but includes multiple character.
The error was solved when I modify it like following,
` qDebug() << "HANDLE DATA RECEIVED CALLED";`

2024-03-28 11:32 UTC, yoshi-nh commented on poc/QtImageRegistration/server.cpp
> +    if (this->m_socket && this->m_socket->state() == QAbstractSocket::ConnectedState) {
I could use this after removing all code in constructor and put
`this->m_socket = 0;`
But not sure whether it is okay or not.

2024-04-01 11:35 UTC, yoshi-nh commented on poc/QtImageRegistration/server.cpp
> +    if (this->m_socket && this->m_socket->state() == QAbstractSocket::ConnectedState) {
Resolve this since we use image-registration-server project instead of QtImageRegistration.

2024-04-01 11:35 UTC, yoshi-nh commented on poc/QtImageRegistration/server.cpp
> +    qDebug() << 'HANDLE DATA RECEIVED CALLED';
We use image-registration-server project instead of this.

2024-04-01 11:36 UTC, yoshi-nh approved these changes

2024-04-01 21:50 UTC, merged